// <auto-generated />
using System;
using Countify.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Countify.Infrastructure.Migrations
{
    [DbContext(typeof(CountifyDbContext))]
    [Migration("20260919192955_RenameBankOpeningBalanceToBalance")]
    partial class RenameBankOpeningBalanceToBalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BudgetControlled")
                        .HasColumnType("bit");

                    b.Property<string>("BudgetLine")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAuxAsset")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuxCxc")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuxCxp")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuxLoan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBankAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOperable")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Month")
                        .IsUnique();

                    b.ToTable("AccountingPeriods", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("AccountingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CutoffDay")
                        .HasColumnType("int");

                    b.Property<string>("DefaultNdNcText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Interest")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountingAccountId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("BankAccounts", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BankReconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BookBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReconciliationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StatementBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.ToTable("BankReconciliations", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BankReconciliationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Beneficiary")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Concept")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CounterpartAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LocalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Reconciled")
                        .HasColumnType("bit");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionTypeValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BankReconciliationId");

                    b.HasIndex("CounterpartAccountId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JournalEntryId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("BankAccountId", "Reference")
                        .IsUnique()
                        .HasFilter("[Reference] IS NOT NULL");

                    b.ToTable("BankTransactions", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BankTransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BankTransactionTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_BankTransactionTypes_TransactionType", "[TransactionType] IN ('DEBITO', 'CREDITO')");
                        });
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYear", "Name")
                        .IsUnique();

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BudgetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("April")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("August")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("December")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("February")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("January")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("July")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("June")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("March")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("May")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("November")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("October")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("September")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("BudgetId", "AccountId", "DepartmentId", "ProjectId")
                        .IsUnique();

                    b.ToTable("BudgetLines", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.CompanySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<bool>("RequireConceptTypes")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireDepartments")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireProjects")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSubProjects")
                        .HasColumnType("bit");

                    b.Property<bool>("UseConceptTypes")
                        .HasColumnType("bit");

                    b.Property<bool>("UseDepartments")
                        .HasColumnType("bit");

                    b.Property<bool>("UseProjects")
                        .HasColumnType("bit");

                    b.Property<bool>("UseSubProjects")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DefaultDepartmentId");

                    b.HasIndex("DefaultProjectId");

                    b.ToTable("CompanySettings", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("CreditTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebitTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DifferenceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EntryGid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntryNumber")
                        .HasColumnType("int");

                    b.Property<string>("Observations")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceModule")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("TypeId");

                    b.ToTable("JournalEntries", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.JournalEntryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppliesToPayableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppliesToReceivableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concept")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EntryConceptType")
                        .HasColumnType("int");

                    b.Property<Guid?>("FixedAssetMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LineGid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoanCertificateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JournalEntryId");

                    b.HasIndex("ProjectId");

                    b.ToTable("JournalEntryLines", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.ProductAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CostAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IncomeAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QualityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CostAccountId");

                    b.HasIndex("IncomeAccountId");

                    b.HasIndex("InventoryAccountId");

                    b.HasIndex("ProductId");

                    b.HasIndex("QualityId");

                    b.HasIndex("ProductId", "QualityId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductAccounts_ProductId_QualityId")
                        .HasFilter("[QualityId] IS NOT NULL");

                    b.ToTable("ProductAccounts", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.ProjectGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProjectGroups", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.Quality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Qualities", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.YearEndClosingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("YearEndClosingEntries", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Audit.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-0000-0000-0000-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1b2c3d4-0000-0000-0000-000000000001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@nexum.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            IsActive = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@NEXUM.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEK8bEtGtCb/UDoybN4kOqOuD3301RFO4res70fBHqEQHqTue2QGGOoUlkc+4MI/2ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a1b2c3d4-0000-0000-0000-000000000001",
                            TwoFactorEnabled = false,
                            UserName = "superadmin"
                        });
                });

            modelBuilder.Entity("Countify.Domain.Entities.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Crear usuarios.",
                            Name = "CanCreateUsers"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Editar usuarios.",
                            Name = "CanEditUsers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Eliminar usuarios.",
                            Name = "CanDeleteUsers"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ver usuarios.",
                            Name = "CanViewUsers"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Crear roles.",
                            Name = "CanCreateRoles"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Editar roles y sus permisos.",
                            Name = "CanEditRoles"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Eliminar roles.",
                            Name = "CanDeleteRoles"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ver roles.",
                            Name = "CanViewRoles"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ver historial.",
                            Name = "CanViewHistorie"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ver departamentos.",
                            Name = "CanViewDepartments"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Crear departamentos.",
                            Name = "CanCreateDepartments"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Editar departamentos.",
                            Name = "CanEditDepartments"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Eliminar departamentos.",
                            Name = "CanDeleteDepartments"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Ver grupos de proyectos.",
                            Name = "CanViewProjectGroups"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Crear grupos de proyectos.",
                            Name = "CanCreateProjectGroups"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Editar grupos de proyectos.",
                            Name = "CanEditProjectGroups"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Eliminar grupos de proyectos.",
                            Name = "CanDeleteProjectGroups"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Ver proyectos.",
                            Name = "CanViewProjects"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Crear proyectos.",
                            Name = "CanCreateProjects"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Editar proyectos.",
                            Name = "CanEditProjects"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Eliminar proyectos.",
                            Name = "CanDeleteProjects"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Ver tipos de documento.",
                            Name = "CanViewDocumentTypes"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Crear tipos de documento.",
                            Name = "CanCreateDocumentTypes"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Editar tipos de documento.",
                            Name = "CanEditDocumentTypes"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Eliminar tipos de documento.",
                            Name = "CanDeleteDocumentTypes"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Ver cuentas contables.",
                            Name = "CanViewAccounts"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Crear cuentas contables.",
                            Name = "CanCreateAccounts"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Editar cuentas contables.",
                            Name = "CanEditAccounts"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Eliminar cuentas contables.",
                            Name = "CanDeleteAccounts"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Ver cuentas por producto.",
                            Name = "CanViewProductAccounts"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Crear cuentas por producto.",
                            Name = "CanCreateProductAccounts"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Editar cuentas por producto.",
                            Name = "CanEditProductAccounts"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Eliminar cuentas por producto.",
                            Name = "CanDeleteProductAccounts"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Ver períodos contables.",
                            Name = "CanViewAccountingPeriods"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Crear períodos contables.",
                            Name = "CanCreateAccountingPeriods"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Editar períodos contables.",
                            Name = "CanEditAccountingPeriods"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Eliminar períodos contables.",
                            Name = "CanDeleteAccountingPeriods"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Cerrar períodos contables.",
                            Name = "CanCloseAccountingPeriods"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Ver partidas.",
                            Name = "CanViewJournalEntries"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Crear partidas.",
                            Name = "CanCreateJournalEntries"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Editar partidas.",
                            Name = "CanEditJournalEntries"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Eliminar partidas.",
                            Name = "CanDeleteJournalEntries"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Aprobar partidas.",
                            Name = "CanApproveJournalEntries"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Contabilizar partidas.",
                            Name = "CanPostJournalEntries"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Anular partidas.",
                            Name = "CanVoidJournalEntries"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Ver configuración contable.",
                            Name = "CanViewCompanySettings"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Editar configuración contable.",
                            Name = "CanEditCompanySettings"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Ver reportes contables.",
                            Name = "CanViewReports"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Ver presupuestos.",
                            Name = "CanViewBudgets"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Crear presupuestos.",
                            Name = "CanCreateBudgets"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Editar presupuestos.",
                            Name = "CanEditBudgets"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Eliminar presupuestos.",
                            Name = "CanDeleteBudgets"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Ver cuentas bancarias.",
                            Name = "CanViewBankAccounts"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Crear cuentas bancarias.",
                            Name = "CanCreateBankAccounts"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Editar cuentas bancarias.",
                            Name = "CanEditBankAccounts"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Eliminar cuentas bancarias.",
                            Name = "CanDeleteBankAccounts"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Ver tipos de movimientos bancarios.",
                            Name = "CanViewBankTransactionTypes"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Crear tipos de movimientos bancarios.",
                            Name = "CanCreateBankTransactionTypes"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Editar tipos de movimientos bancarios.",
                            Name = "CanEditBankTransactionTypes"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Eliminar tipos de movimientos bancarios.",
                            Name = "CanDeleteBankTransactionTypes"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Ver movimientos bancarios.",
                            Name = "CanViewBankTransactions"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Crear movimientos bancarios.",
                            Name = "CanCreateBankTransactions"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Editar movimientos bancarios.",
                            Name = "CanEditBankTransactions"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Eliminar movimientos bancarios.",
                            Name = "CanDeleteBankTransactions"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Ver conciliaciones bancarias.",
                            Name = "CanViewBankReconciliations"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Crear conciliaciones bancarias.",
                            Name = "CanCreateBankReconciliations"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Editar conciliaciones bancarias.",
                            Name = "CanEditBankReconciliations"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Desmarcar movimientos conciliados.",
                            Name = "CanUnreconcileBankTransactions"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Ver monedas.",
                            Name = "CanViewCurrencies"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Crear monedas.",
                            Name = "CanCreateCurrencies"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Editar monedas.",
                            Name = "CanEditCurrencies"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Eliminar monedas.",
                            Name = "CanDeleteCurrencies"
                        });
                });

            modelBuilder.Entity("Countify.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 39
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 40
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 44
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 45
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 46
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 47
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 48
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 49
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 50
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 51
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 52
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 53
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 54
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 55
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 56
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 57
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 58
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 59
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 60
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 61
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 62
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 63
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 64
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 65
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 66
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 67
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 68
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 69
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 70
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 71
                        },
                        new
                        {
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001",
                            PermissionId = 72
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f3d1e2c4-0000-0000-0000-000000000001",
                            ConcurrencyStamp = "f3d1e2c4-0000-0000-0000-000000000001",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "f3d1e2c4-0000-0000-0000-000000000002",
                            ConcurrencyStamp = "f3d1e2c4-0000-0000-0000-000000000002",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a1b2c3d4-0000-0000-0000-000000000001",
                            RoleId = "f3d1e2c4-0000-0000-0000-000000000001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BankAccount", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Accounting.Account", "AccountingAccount")
                        .WithMany()
                        .HasForeignKey("AccountingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Countify.Domain.Entities.Accounting.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccountingAccount");

                    b.Navigation("Currency");

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BankReconciliation", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Accounting.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BankTransaction", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Accounting.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.BankReconciliation", "BankReconciliation")
                        .WithMany("Transactions")
                        .HasForeignKey("BankReconciliationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Countify.Domain.Entities.Accounting.Account", "CounterpartAccount")
                        .WithMany()
                        .HasForeignKey("CounterpartAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Countify.Domain.Entities.Accounting.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Countify.Domain.Entities.Accounting.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Countify.Domain.Entities.Accounting.BankTransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("BankReconciliation");

                    b.Navigation("CounterpartAccount");

                    b.Navigation("Currency");

                    b.Navigation("Department");

                    b.Navigation("JournalEntry");

                    b.Navigation("Project");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BudgetLine", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Accounting.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Budget", "Budget")
                        .WithMany("Lines")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Budget");

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.CompanySettings", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Accounting.Department", "DefaultDepartment")
                        .WithMany()
                        .HasForeignKey("DefaultDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Countify.Domain.Entities.Accounting.Project", "DefaultProject")
                        .WithMany()
                        .HasForeignKey("DefaultProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultDepartment");

                    b.Navigation("DefaultProject");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.JournalEntry", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Accounting.AccountingPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Countify.Domain.Entities.Accounting.DocumentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.JournalEntryLine", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Accounting.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Countify.Domain.Entities.Accounting.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Department");

                    b.Navigation("JournalEntry");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.ProductAccount", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Accounting.Account", "CostAccount")
                        .WithMany()
                        .HasForeignKey("CostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Account", "IncomeAccount")
                        .WithMany()
                        .HasForeignKey("IncomeAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Account", "InventoryAccount")
                        .WithMany()
                        .HasForeignKey("InventoryAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Accounting.Quality", "Quality")
                        .WithMany()
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CostAccount");

                    b.Navigation("IncomeAccount");

                    b.Navigation("InventoryAccount");

                    b.Navigation("Product");

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.Project", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Accounting.ProjectGroup", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Auth.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Countify.Domain.Entities.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Countify.Domain.Entities.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.BankReconciliation", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.Budget", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Countify.Domain.Entities.Accounting.ProjectGroup", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
