using AutoMapper;
using Countify.Application.Wrappers;
using Countify.Domain.Entities.Accounting;
using Countify.Domain.Enums;
using Countify.Domain.Interfaces;
using Countify.Domain.Seeders;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Countify.Application.Features.Banks;

public class BankAccountDto
{
    public Guid Id { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = "";
    public string AccountNumber { get; set; } = ""; public Guid AccountingAccountId { get; set; } public string? AccountingAccountCode { get; set; }
    public string? AccountingAccountName { get; set; } public Guid CurrencyId { get; set; } public string? CurrencyCode { get; set; } public string? CurrencyName { get; set; } public int? CutoffDay { get; set; }
    public string? CheckNumber { get; set; } public decimal Interest { get; set; } public decimal Balance { get; set; }
    public Guid? DepartmentId { get; set; } public Guid? ProjectId { get; set; } public bool IsInactive { get; set; } public string? DefaultNdNcText { get; set; }
}
public class BankTransactionTypeDto { public Guid Id { get; set; } public string Code { get; set; } = ""; public string MovementType { get; set; } = ""; public string TransactionType { get; set; } = ""; }
public class BankTransactionDto
{
    public Guid Id { get; set; } public Guid BankAccountId { get; set; } public string? BankAccountName { get; set; } public Guid TransactionTypeId { get; set; }
    public string? TransactionTypeCode { get; set; } public string TransactionTypeValue { get; set; } = ""; public DateTime Date { get; set; }
    public Guid CurrencyId { get; set; } public string? CurrencyCode { get; set; } public decimal ExchangeRate { get; set; } public decimal Amount { get; set; } public decimal LocalAmount { get; set; }
    public string? Reference { get; set; } public string? Beneficiary { get; set; } public string? Concept { get; set; } public Guid? DepartmentId { get; set; }
    public Guid? ProjectId { get; set; } public bool Reconciled { get; set; } public bool Voided { get; set; } public Guid? JournalEntryId { get; set; }
    public Guid CounterpartAccountId { get; set; } public Guid? BankReconciliationId { get; set; }
}
public class BankReconciliationDto
{
    public Guid Id { get; set; } public Guid BankAccountId { get; set; } public string? BankAccountName { get; set; }
    public DateTime ReconciliationDate { get; set; } public decimal StatementBalance { get; set; } public decimal BookBalance { get; set; }
    public bool IsClosed { get; set; } public string? Notes { get; set; } public int TransactionCount { get; set; }
}
public class BankStatementDto
{
    public Guid BankAccountId { get; set; } public string BankAccountName { get; set; } = ""; public DateTime FromDate { get; set; } public DateTime ToDate { get; set; }
    public decimal OpeningBalance { get; set; } public decimal DebitTotal { get; set; } public decimal CreditTotal { get; set; } public decimal ClosingBalance { get; set; }
    public List<BankTransactionDto> Transactions { get; set; } = [];
}
public class BankAccountProfile : Profile
{
    public BankAccountProfile()
    {
        CreateMap<BankAccount, BankAccountDto>().ForMember(d => d.AccountingAccountCode, o => o.MapFrom(s => s.AccountingAccount!.Code)).ForMember(d => d.AccountingAccountName, o => o.MapFrom(s => s.AccountingAccount!.Name)).ForMember(d => d.CurrencyCode, o => o.MapFrom(s => s.Currency!.Code)).ForMember(d => d.CurrencyName, o => o.MapFrom(s => s.Currency!.Name));
        CreateMap<BankTransactionType, BankTransactionTypeDto>();
        CreateMap<BankTransaction, BankTransactionDto>().ForMember(d => d.BankAccountName, o => o.MapFrom(s => s.BankAccount!.Name)).ForMember(d => d.TransactionTypeCode, o => o.MapFrom(s => s.TransactionType!.Code)).ForMember(d => d.CurrencyCode, o => o.MapFrom(s => s.Currency!.Code));
        CreateMap<BankReconciliation, BankReconciliationDto>().ForMember(d => d.BankAccountName, o => o.MapFrom(s => s.BankAccount!.Name)).ForMember(d => d.TransactionCount, o => o.MapFrom(s => s.Transactions.Count));
    }
}

public record CreateBankAccountCommand(string Code, string Name, string AccountNumber, Guid AccountingAccountId, Guid CurrencyId, int? CutoffDay, string? CheckNumber, decimal Interest, decimal Balance, Guid? DepartmentId, Guid? ProjectId, bool IsInactive, string? DefaultNdNcText) : IRequest<Response<Guid>>;
public record UpdateBankAccountCommand(Guid Id, string Code, string Name, string AccountNumber, Guid AccountingAccountId, Guid CurrencyId, int? CutoffDay, string? CheckNumber, decimal Interest, decimal Balance, Guid? DepartmentId, Guid? ProjectId, bool IsInactive, string? DefaultNdNcText) : IRequest<Response<bool>>;
public record DeleteBankAccountCommand(Guid Id) : IRequest<Response<bool>>;
public record GetBankAccountsQuery : IRequest<Response<List<BankAccountDto>>>;
public record CreateBankTransactionTypeCommand(string Code, string MovementType, string TransactionType) : IRequest<Response<Guid>>;
public record UpdateBankTransactionTypeCommand(Guid Id, string Code, string MovementType, string TransactionType) : IRequest<Response<bool>>;
public record DeleteBankTransactionTypeCommand(Guid Id) : IRequest<Response<bool>>;
public record GetBankTransactionTypesQuery : IRequest<Response<List<BankTransactionTypeDto>>>;
 public record CreateBankTransactionCommand(Guid BankAccountId, Guid TransactionTypeId, string TransactionTypeValue, DateTime Date, Guid CurrencyId, decimal ExchangeRate, decimal Amount, decimal LocalAmount, string? Reference, string? Beneficiary, string? Concept, Guid? DepartmentId, Guid? ProjectId, bool Reconciled, bool Voided, Guid? JournalEntryId, Guid CounterpartAccountId) : IRequest<Response<Guid>>;
 public record UpdateBankTransactionCommand(Guid Id, Guid BankAccountId, Guid TransactionTypeId, string TransactionTypeValue, DateTime Date, Guid CurrencyId, decimal ExchangeRate, decimal Amount, decimal LocalAmount, string? Reference, string? Beneficiary, string? Concept, Guid? DepartmentId, Guid? ProjectId, bool Reconciled, bool Voided, Guid? JournalEntryId, Guid CounterpartAccountId) : IRequest<Response<bool>>;
 public record VoidBankTransactionCommand(Guid Id) : IRequest<Response<bool>>;
public record DeleteBankTransactionCommand(Guid Id) : IRequest<Response<bool>>;
 public record GetBankTransactionsQuery(Guid? BankAccountId = null) : IRequest<Response<List<BankTransactionDto>>>;
public record CreateBankReconciliationCommand(Guid BankAccountId, DateTime ReconciliationDate, decimal StatementBalance, decimal BookBalance, string? Notes, List<Guid> TransactionIds) : IRequest<Response<Guid>>;
public record GetBankReconciliationsQuery : IRequest<Response<List<BankReconciliationDto>>>;
 public record SetBankTransactionReconciliationCommand(Guid ReconciliationId, Guid TransactionId, bool Reconciled) : IRequest<Response<bool>>;
 public record UnreconcileBankTransactionCommand(Guid Id) : IRequest<Response<bool>>;
 public record CloseBankReconciliationCommand(Guid Id) : IRequest<Response<bool>>;
public record GetBankStatementQuery(Guid BankAccountId, DateTime FromDate, DateTime ToDate) : IRequest<Response<BankStatementDto>>;

public class BankHandler(IUnitOfWork u, IMapper m) :
    IRequestHandler<CreateBankAccountCommand, Response<Guid>>, IRequestHandler<UpdateBankAccountCommand, Response<bool>>, IRequestHandler<DeleteBankAccountCommand, Response<bool>>, IRequestHandler<GetBankAccountsQuery, Response<List<BankAccountDto>>>,
    IRequestHandler<CreateBankTransactionTypeCommand, Response<Guid>>, IRequestHandler<UpdateBankTransactionTypeCommand, Response<bool>>, IRequestHandler<DeleteBankTransactionTypeCommand, Response<bool>>, IRequestHandler<GetBankTransactionTypesQuery, Response<List<BankTransactionTypeDto>>>,
     IRequestHandler<CreateBankTransactionCommand, Response<Guid>>, IRequestHandler<UpdateBankTransactionCommand, Response<bool>>, IRequestHandler<VoidBankTransactionCommand, Response<bool>>, IRequestHandler<DeleteBankTransactionCommand, Response<bool>>, IRequestHandler<GetBankTransactionsQuery, Response<List<BankTransactionDto>>>,
     IRequestHandler<CreateBankReconciliationCommand, Response<Guid>>, IRequestHandler<GetBankReconciliationsQuery, Response<List<BankReconciliationDto>>>, IRequestHandler<SetBankTransactionReconciliationCommand, Response<bool>>, IRequestHandler<UnreconcileBankTransactionCommand, Response<bool>>, IRequestHandler<CloseBankReconciliationCommand, Response<bool>>, IRequestHandler<GetBankStatementQuery, Response<BankStatementDto>>
{
     public async Task<Response<Guid>> Handle(CreateBankAccountCommand x, CancellationToken c) { if (await u.BankAccounts.ExistsAsync(a => a.Code == x.Code, c)) return Response<Guid>.Failure("El código del banco ya existe."); if (!await u.Accounts.ExistsAsync(a => a.Id == x.AccountingAccountId && a.IsBankAccount, c)) return Response<Guid>.Failure("La cuenta contable debe ser una cuenta bancaria válida."); if (!await u.Currencies.ExistsAsync(v => v.Id == x.CurrencyId && v.IsActive, c)) return Response<Guid>.Failure("La moneda no existe o está inactiva."); var e = new BankAccount { Code=x.Code.Trim(), Name=x.Name.Trim(), AccountNumber=x.AccountNumber.Trim(), AccountingAccountId=x.AccountingAccountId, CurrencyId=x.CurrencyId, CutoffDay=x.CutoffDay, CheckNumber=x.CheckNumber, Interest=x.Interest, Balance=x.Balance, DepartmentId=x.DepartmentId, ProjectId=x.ProjectId, IsInactive=x.IsInactive, DefaultNdNcText=x.DefaultNdNcText }; await u.BankAccounts.AddAsync(e,c); await u.SaveChangesAsync(c); return Response<Guid>.Success(e.Id,201); }
     public async Task<Response<bool>> Handle(UpdateBankAccountCommand x, CancellationToken c) { var e=await u.BankAccounts.GetByIdAsync(x.Id,c); if(e is null)return Response<bool>.NotFound("Banco no encontrado."); if(await u.BankAccounts.ExistsAsync(a=>a.Code==x.Code&&a.Id!=x.Id,c))return Response<bool>.Failure("El código del banco ya existe."); if(!await u.Accounts.ExistsAsync(a=>a.Id==x.AccountingAccountId&&a.IsBankAccount,c))return Response<bool>.Failure("La cuenta contable debe ser una cuenta bancaria válida."); if(!await u.Currencies.ExistsAsync(v=>v.Id==x.CurrencyId&&v.IsActive,c))return Response<bool>.Failure("La moneda no existe o está inactiva."); e.Code=x.Code.Trim();e.Name=x.Name.Trim();e.AccountNumber=x.AccountNumber.Trim();e.AccountingAccountId=x.AccountingAccountId;e.CurrencyId=x.CurrencyId;e.CutoffDay=x.CutoffDay;e.CheckNumber=x.CheckNumber;e.Interest=x.Interest;e.Balance=x.Balance;e.DepartmentId=x.DepartmentId;e.ProjectId=x.ProjectId;e.IsInactive=x.IsInactive;e.DefaultNdNcText=x.DefaultNdNcText;await u.SaveChangesAsync(c);return Response<bool>.Success(true,204); }
    public async Task<Response<bool>> Handle(DeleteBankAccountCommand x,CancellationToken c){var e=await u.BankAccounts.GetByIdAsync(x.Id,c);if(e is null)return Response<bool>.NotFound("Banco no encontrado.");if(await u.BankTransactions.ExistsAsync(t=>t.BankAccountId==x.Id,c))return Response<bool>.Failure("No se puede eliminar un banco con movimientos.");await u.BankAccounts.DeleteAsync(e,c);await u.SaveChangesAsync(c);return Response<bool>.Success(true,204);}
    public async Task<Response<List<BankAccountDto>>> Handle(GetBankAccountsQuery x,CancellationToken c)=>Response<List<BankAccountDto>>.Success(m.Map<List<BankAccountDto>>(await u.BankAccounts.ToListAsync(u.BankAccounts.Query().Include(a=>a.AccountingAccount).Include(a=>a.Currency).OrderBy(a=>a.Code),c)));
    public async Task<Response<Guid>> Handle(CreateBankTransactionTypeCommand x,CancellationToken c){if(await u.BankTransactionTypes.ExistsAsync(t=>t.Code==x.Code,c))return Response<Guid>.Failure("El código del tipo ya existe.");var e=new BankTransactionType{Code=x.Code.Trim(),MovementType=x.MovementType,TransactionType=x.TransactionType};await u.BankTransactionTypes.AddAsync(e,c);await u.SaveChangesAsync(c);return Response<Guid>.Success(e.Id,201);}
    public async Task<Response<bool>> Handle(UpdateBankTransactionTypeCommand x,CancellationToken c){var e=await u.BankTransactionTypes.GetByIdAsync(x.Id,c);if(e is null)return Response<bool>.NotFound("Tipo de movimiento no encontrado.");if(await u.BankTransactionTypes.ExistsAsync(t=>t.Code==x.Code&&t.Id!=x.Id,c))return Response<bool>.Failure("El código del tipo ya existe.");e.Code=x.Code.Trim();e.MovementType=x.MovementType;e.TransactionType=x.TransactionType;await u.SaveChangesAsync(c);return Response<bool>.Success(true,204);}
    public async Task<Response<bool>> Handle(DeleteBankTransactionTypeCommand x,CancellationToken c){var e=await u.BankTransactionTypes.GetByIdAsync(x.Id,c);if(e is null)return Response<bool>.NotFound("Tipo de movimiento no encontrado.");if(await u.BankTransactions.ExistsAsync(t=>t.TransactionTypeId==x.Id,c))return Response<bool>.Failure("No se puede eliminar un tipo usado en movimientos.");await u.BankTransactionTypes.DeleteAsync(e,c);await u.SaveChangesAsync(c);return Response<bool>.Success(true,204);}
    public async Task<Response<List<BankTransactionTypeDto>>> Handle(GetBankTransactionTypesQuery x,CancellationToken c)=>Response<List<BankTransactionTypeDto>>.Success(m.Map<List<BankTransactionTypeDto>>(await u.BankTransactionTypes.ToListAsync(u.BankTransactionTypes.Query().OrderBy(t=>t.Code),c)));
        private async Task<string?> ValidateTransaction(Guid bank,Guid type,Guid counterpart,decimal amount,DateTime date,CancellationToken c){var bankAccount=await u.BankAccounts.Query().FirstOrDefaultAsync(a=>a.Id==bank&&!a.IsInactive,c);if(bankAccount is null)return "El banco no existe o está inactivo.";if(!await u.Accounts.ExistsAsync(a=>a.Id==bankAccount.AccountingAccountId&&a.IsBankAccount,c))return "La cuenta contable del banco no existe o no es bancaria.";if(bankAccount.AccountingAccountId==counterpart)return "La cuenta contraparte debe ser distinta de la cuenta contable del banco.";var movement=await u.BankTransactionTypes.GetByIdAsync(type,c);if(movement is null)return "El tipo de movimiento no existe.";if(!string.Equals(movement.TransactionType,"DEBITO",StringComparison.OrdinalIgnoreCase)&&!string.Equals(movement.TransactionType,"CREDITO",StringComparison.OrdinalIgnoreCase))return "El tipo debe ser débito o crédito.";if(amount<=0)return "El importe debe ser mayor que cero.";if(!await u.Accounts.ExistsAsync(a=>a.Id==counterpart&&a.IsOperable,c))return "La cuenta contraparte no existe o no es operable.";var period=await u.AccountingPeriods.Query().FirstOrDefaultAsync(p=>p.Month.Month==date.Month&&p.Month.Year==date.Year,c);if(period is null)return "No existe período contable para la fecha.";return period.IsClosed?"El período contable está cerrado.":null;}
      private async Task PrepareTransactionAsync(BankTransaction e, string? requestedReference, CancellationToken c)
      {
          var bank = await u.BankAccounts.GetByIdAsync(e.BankAccountId, c);
          var type = await u.BankTransactionTypes.GetByIdAsync(e.TransactionTypeId, c);
          if (bank is null || type is null) return;
          e.CurrencyId = bank.CurrencyId;
           e.DepartmentId ??= bank.DepartmentId;
           e.ProjectId ??= bank.ProjectId;
          e.TransactionTypeValue = type?.TransactionType ?? e.TransactionTypeValue;
          var currency = await u.Currencies.GetByIdAsync(e.CurrencyId, c);
          e.ExchangeRate = currency?.ExchangeRate > 0 ? currency.ExchangeRate : 1;
          e.LocalAmount = decimal.Round(e.Amount * e.ExchangeRate, 2, MidpointRounding.AwayFromZero);
          if (string.IsNullOrWhiteSpace(requestedReference) && type.Code.Equals("CHEQUE", StringComparison.OrdinalIgnoreCase))
          {
              var next = int.TryParse(bank.CheckNumber, out var current) ? current + 1 : 1;
              bank.CheckNumber = next.ToString();
              e.Reference = bank.CheckNumber;
          }
          else
              e.Reference = string.IsNullOrWhiteSpace(requestedReference) ? BuildAutomaticReference(e, bank, type) : requestedReference.Trim();
          if (string.IsNullOrWhiteSpace(e.Beneficiary) && type.MovementType.Contains("DEPOSITO", StringComparison.OrdinalIgnoreCase))
              e.Beneficiary = "DEPOSITO DE HOY";
          if (string.IsNullOrWhiteSpace(e.Beneficiary) && (type.Code.Equals("NC", StringComparison.OrdinalIgnoreCase) || type.Code.Equals("ND", StringComparison.OrdinalIgnoreCase) || type.Code.Equals("NDNC", StringComparison.OrdinalIgnoreCase) || type.Code.Equals("NDDN", StringComparison.OrdinalIgnoreCase)))
              e.Beneficiary = bank.DefaultNdNcText;
          if (e.CurrencyId == Guid.Empty && bank is not null) e.CurrencyId = bank.CurrencyId;
     }
     private static string? BuildAutomaticReference(BankTransaction e, BankAccount? bank, BankTransactionType? type)
     {
         var code = type?.Code?.ToUpperInvariant();
          if (code is "CHEQUE" or "CHQ") return string.IsNullOrWhiteSpace(bank?.CheckNumber) ? $"CHEQUE-{e.Id:N}" : bank.CheckNumber;
          if (code is "NDNC" or "NC" or "ND" or "NDDN") return $"{(type?.MovementType?.Contains("DEBITO", StringComparison.OrdinalIgnoreCase) == true ? "ND" : "NC")}-{e.Id:N}";
          if (type?.MovementType?.Contains("DEPOSITO", StringComparison.OrdinalIgnoreCase) == true) return $"DEPOSITO-{e.Id:N}";
         return null;
     }
       public async Task<Response<Guid>> Handle(CreateBankTransactionCommand x,CancellationToken c){var error=await ValidateTransaction(x.BankAccountId,x.TransactionTypeId,x.CounterpartAccountId,x.Amount,x.Date,c);if(error!=null)return Response<Guid>.Failure(error);var e=new BankTransaction{Id=Guid.NewGuid(),BankAccountId=x.BankAccountId,TransactionTypeId=x.TransactionTypeId,Date=x.Date,CurrencyId=x.CurrencyId,ExchangeRate=x.ExchangeRate,Amount=x.Amount,LocalAmount=x.LocalAmount,Reference=x.Reference,Beneficiary=x.Beneficiary,Concept=x.Concept,DepartmentId=x.DepartmentId,ProjectId=x.ProjectId,Reconciled=false,Voided=false,CounterpartAccountId=x.CounterpartAccountId};await PrepareTransactionAsync(e,x.Reference,c);await u.BankTransactions.AddAsync(e,c);await CreateOrUpdateJournalAsync(e,null,c);await u.SaveChangesAsync(c);return Response<Guid>.Success(e.Id,201);}
        public async Task<Response<bool>> Handle(UpdateBankTransactionCommand x,CancellationToken c){var e=await u.BankTransactions.Query().Include(t=>t.JournalEntry).ThenInclude(j=>j!.Lines).FirstOrDefaultAsync(t=>t.Id==x.Id,c);if(e is null)return Response<bool>.NotFound("Movimiento bancario no encontrado.");if(e.Reconciled)return Response<bool>.Failure("No se puede modificar un movimiento conciliado.");if(e.Voided)return Response<bool>.Failure("Un movimiento anulado no se puede editar.");if(e.JournalEntry?.PeriodId is Guid oldPeriodId&&await u.AccountingPeriods.ExistsAsync(p=>p.Id==oldPeriodId&&p.IsClosed,c))return Response<bool>.Failure("El período de la partida automática está cerrado.");var error=await ValidateTransaction(x.BankAccountId,x.TransactionTypeId,x.CounterpartAccountId,x.Amount,x.Date,c);if(error!=null)return Response<bool>.Failure(error);e.BankAccountId=x.BankAccountId;e.TransactionTypeId=x.TransactionTypeId;e.Date=x.Date;e.CurrencyId=x.CurrencyId;e.ExchangeRate=x.ExchangeRate;e.Amount=x.Amount;e.LocalAmount=x.LocalAmount;e.Reference=x.Reference;e.Beneficiary=x.Beneficiary;e.Concept=x.Concept;e.DepartmentId=x.DepartmentId;e.ProjectId=x.ProjectId;e.CounterpartAccountId=x.CounterpartAccountId;await PrepareTransactionAsync(e,x.Reference,c);await CreateOrUpdateJournalAsync(e,e.JournalEntry,c);await u.SaveChangesAsync(c);return Response<bool>.Success(true,204);}
     public async Task<Response<bool>> Handle(VoidBankTransactionCommand x,CancellationToken c){var e=await u.BankTransactions.Query().Include(t=>t.JournalEntry).FirstOrDefaultAsync(t=>t.Id==x.Id,c);if(e is null)return Response<bool>.NotFound("Movimiento bancario no encontrado.");if(e.Reconciled)return Response<bool>.Failure("No se puede anular un movimiento conciliado.");if(e.Voided)return Response<bool>.Failure("El movimiento ya está anulado.");if(e.JournalEntry?.PeriodId is Guid periodId&&await u.AccountingPeriods.ExistsAsync(p=>p.Id==periodId&&p.IsClosed,c))return Response<bool>.Failure("El período de la partida automática está cerrado.");e.Voided=true;if(e.JournalEntry is not null)e.JournalEntry.Status=JournalEntryStatus.Voided;await u.SaveChangesAsync(c);return Response<bool>.Success(true,204);}
    public async Task<Response<bool>> Handle(DeleteBankTransactionCommand x,CancellationToken c){var e=await u.BankTransactions.Query().Include(t=>t.JournalEntry).FirstOrDefaultAsync(t=>t.Id==x.Id,c);if(e is null)return Response<bool>.NotFound("Movimiento bancario no encontrado.");if(e.Reconciled)return Response<bool>.Failure("No se puede eliminar un movimiento conciliado.");if(e.JournalEntry?.PeriodId is Guid periodId&&await u.AccountingPeriods.ExistsAsync(p=>p.Id==periodId&&p.IsClosed,c))return Response<bool>.Failure("El período de la partida automática está cerrado.");if(e.JournalEntry is not null)await u.JournalEntries.DeleteAsync(e.JournalEntry,c);await u.BankTransactions.DeleteAsync(e,c);await u.SaveChangesAsync(c);return Response<bool>.Success(true,204);}
      public async Task<Response<List<BankTransactionDto>>> Handle(GetBankTransactionsQuery x,CancellationToken c)=>Response<List<BankTransactionDto>>.Success(m.Map<List<BankTransactionDto>>(await u.BankTransactions.ToListAsync(u.BankTransactions.Query().Include(t=>t.BankAccount).Include(t=>t.TransactionType).Include(t=>t.Currency).Where(t=>!x.BankAccountId.HasValue||t.BankAccountId==x.BankAccountId).OrderByDescending(t=>t.Date),c)));
     public async Task<Response<Guid>> Handle(CreateBankReconciliationCommand x,CancellationToken c){var bank=await u.BankAccounts.GetByIdAsync(x.BankAccountId,c);if(bank is null)return Response<Guid>.NotFound("Banco no encontrado.");if(x.TransactionIds.Count==0)return Response<Guid>.Failure("Seleccione al menos un movimiento.");var tx=await u.BankTransactions.ToListAsync(u.BankTransactions.Query().Include(t=>t.TransactionType).Where(t=>x.TransactionIds.Contains(t.Id)&&t.BankAccountId==x.BankAccountId),c);if(tx.Count!=x.TransactionIds.Distinct().Count())return Response<Guid>.Failure("Hay movimientos inválidos para el banco seleccionado.");if(tx.Any(t=>t.Reconciled||t.Voided))return Response<Guid>.Failure("No se pueden conciliar movimientos anulados o ya conciliados.");var all=await u.BankTransactions.ToListAsync(u.BankTransactions.Query().Include(t=>t.TransactionType).Where(t=>t.BankAccountId==x.BankAccountId&&!t.Voided&&t.Date<=x.ReconciliationDate),c);var bookBalance=bank.Balance+all.Where(IsDebit).Sum(t=>t.LocalAmount)-all.Where(t=>!IsDebit(t)).Sum(t=>t.LocalAmount);var r=await u.BankReconciliations.Query().FirstOrDefaultAsync(r=>r.BankAccountId==x.BankAccountId&&!r.IsClosed,c);var created=r is null;if(r is null){r=new BankReconciliation{BankAccountId=x.BankAccountId,IsClosed=false};await u.BankReconciliations.AddAsync(r,c);}r.ReconciliationDate=x.ReconciliationDate;r.StatementBalance=x.StatementBalance;r.BookBalance=bookBalance;r.Notes=x.Notes;foreach(var t in tx){t.Reconciled=true;t.BankReconciliation=r;}await u.SaveChangesAsync(c);return Response<Guid>.Success(r.Id,created?201:200);}
    public async Task<Response<List<BankReconciliationDto>>> Handle(GetBankReconciliationsQuery x,CancellationToken c)=>Response<List<BankReconciliationDto>>.Success(m.Map<List<BankReconciliationDto>>(await u.BankReconciliations.ToListAsync(u.BankReconciliations.Query().Include(r=>r.BankAccount).Include(r=>r.Transactions).OrderByDescending(r=>r.ReconciliationDate),c)));
     public async Task<Response<bool>> Handle(SetBankTransactionReconciliationCommand x,CancellationToken c){var r=await u.BankReconciliations.GetByIdAsync(x.ReconciliationId,c);var t=await u.BankTransactions.Query().Include(t=>t.BankReconciliation).FirstOrDefaultAsync(t=>t.Id==x.TransactionId,c);if(r is null||t is null||r.BankAccountId!=t.BankAccountId)return Response<bool>.NotFound("Conciliación o movimiento no encontrado.");if(r.IsClosed||t.BankReconciliation?.IsClosed==true)return Response<bool>.Failure("La conciliación está cerrada.");if(t.Voided)return Response<bool>.Failure("No se puede conciliar un movimiento anulado.");if(x.Reconciled&&t.Reconciled)return Response<bool>.Failure("El movimiento ya está conciliado.");t.Reconciled=x.Reconciled;t.BankReconciliationId=x.Reconciled?r.Id:null;await u.SaveChangesAsync(c);return Response<bool>.Success(true,204);}
      public async Task<Response<bool>> Handle(UnreconcileBankTransactionCommand x,CancellationToken c){var t=await u.BankTransactions.Query().Include(t=>t.BankReconciliation).FirstOrDefaultAsync(t=>t.Id==x.Id,c);if(t is null)return Response<bool>.NotFound("Movimiento bancario no encontrado.");if(t.BankReconciliation?.IsClosed==true)return Response<bool>.Failure("La conciliación está cerrada.");t.Reconciled=false;await u.SaveChangesAsync(c);return Response<bool>.Success(true,204);}
     public async Task<Response<bool>> Handle(CloseBankReconciliationCommand x,CancellationToken c){var r=await u.BankReconciliations.GetByIdAsync(x.Id,c);if(r is null)return Response<bool>.NotFound("Conciliación no encontrada.");if(r.IsClosed)return Response<bool>.Failure("La conciliación ya está cerrada.");r.IsClosed=true;await u.SaveChangesAsync(c);return Response<bool>.Success(true,204);}
      public async Task<Response<BankStatementDto>> Handle(GetBankStatementQuery x,CancellationToken c){if(x.FromDate>x.ToDate)return Response<BankStatementDto>.Failure("El rango de fechas no es válido.");var bank=await u.BankAccounts.GetByIdAsync(x.BankAccountId,c);if(bank is null)return Response<BankStatementDto>.NotFound("Banco no encontrado.");var end=x.ToDate.Date.AddDays(1);var before=await u.BankTransactions.ToListAsync(u.BankTransactions.Query().Include(t=>t.TransactionType).Where(t=>t.BankAccountId==x.BankAccountId&&!t.Voided&&t.Date<x.FromDate),c);var opening=bank.Balance+before.Where(IsDebit).Sum(t=>t.LocalAmount)-before.Where(t=>!IsDebit(t)).Sum(t=>t.LocalAmount);var tx=await u.BankTransactions.ToListAsync(u.BankTransactions.Query().Include(t=>t.BankAccount).Include(t=>t.TransactionType).Include(t=>t.Currency).Where(t=>t.BankAccountId==x.BankAccountId&&!t.Voided&&t.Date>=x.FromDate&&t.Date<end).OrderBy(t=>t.Date),c);var debit=tx.Where(t=>IsDebit(t)).Sum(t=>t.LocalAmount);var credit=tx.Where(t=>!IsDebit(t)).Sum(t=>t.LocalAmount);return Response<BankStatementDto>.Success(new BankStatementDto{BankAccountId=bank.Id,BankAccountName=bank.Name,FromDate=x.FromDate,ToDate=x.ToDate,OpeningBalance=opening,DebitTotal=debit,CreditTotal=credit,ClosingBalance=opening+debit-credit,Transactions=m.Map<List<BankTransactionDto>>(tx)});}
    private static bool IsDebit(BankTransaction t)=>string.Equals(t.TransactionTypeValue,"DEBITO",StringComparison.OrdinalIgnoreCase)||string.Equals(t.TransactionType?.TransactionType,"DEBITO",StringComparison.OrdinalIgnoreCase);
     private async Task CreateOrUpdateJournalAsync(BankTransaction t,JournalEntry? journal,CancellationToken c){var bank=await u.BankAccounts.Query().Include(a=>a.AccountingAccount).FirstAsync(a=>a.Id==t.BankAccountId,c);var type=await u.BankTransactionTypes.GetByIdAsync(t.TransactionTypeId,c);var period=await u.AccountingPeriods.Query().FirstOrDefaultAsync(p=>p.Month.Month==t.Date.Month&&p.Month.Year==t.Date.Year,c);var code=type?.Code.Trim().ToUpper();var movement=type?.MovementType.Trim().ToUpper();var documentType=await u.DocumentTypes.Query().FirstOrDefaultAsync(d=>d.Code.ToUpper()==code||d.Name.ToUpper()==code,c);documentType??=await u.DocumentTypes.Query().FirstOrDefaultAsync(d=>d.Code.ToUpper()==movement||d.Name.ToUpper()==movement,c);var typeId=documentType?.Id??BasicDocumentTypes.Partida.Id;if(journal is null){var periodEntries=period is null?u.JournalEntries.Query():u.JournalEntries.Query().Where(e=>e.PeriodId==period.Id);var max=await periodEntries.Select(e=>(int?)e.EntryNumber).MaxAsync(c);journal=new JournalEntry{TypeId=typeId,PeriodId=period?.Id,EntryNumber=(max??0)+1,ReferenceDate=t.Date,Reference=t.Reference??$"BAN-{t.Id:N}",Concept=t.Concept??t.Beneficiary??"Movimiento bancario",Status=JournalEntryStatus.Posted,SourceModule=SourceModule.Bank,EntryGid=Guid.NewGuid()};await u.JournalEntries.AddAsync(journal,c);t.JournalEntry=journal;}else{journal.TypeId=typeId;journal.PeriodId=period?.Id;journal.ReferenceDate=t.Date;journal.Reference=t.Reference??journal.Reference;journal.Concept=t.Concept??t.Beneficiary??journal.Concept;while(journal.Lines.Count>2){var line=journal.Lines[^1];journal.Lines.Remove(line);await u.JournalEntryLines.DeleteAsync(line,c);}}
         while(journal.Lines.Count<2)journal.Lines.Add(new JournalEntryLine{LineGid=Guid.NewGuid()});
         var debit=string.Equals(type?.TransactionType,"DEBITO",StringComparison.OrdinalIgnoreCase);var bankLine=journal.Lines[0];var counterpartLine=journal.Lines[1];bankLine.AccountId=bank.AccountingAccountId;bankLine.DepartmentId=t.DepartmentId;bankLine.ProjectId=t.ProjectId;bankLine.Concept=t.Concept;bankLine.Debit=debit?t.LocalAmount:0;bankLine.Credit=debit?0:t.LocalAmount;counterpartLine.AccountId=t.CounterpartAccountId;counterpartLine.DepartmentId=t.DepartmentId;counterpartLine.ProjectId=t.ProjectId;counterpartLine.Concept=t.Concept;counterpartLine.Debit=debit?0:t.LocalAmount;counterpartLine.Credit=debit?t.LocalAmount:0;journal.DebitTotal=t.LocalAmount;journal.CreditTotal=t.LocalAmount;journal.DifferenceAmount=0;t.JournalEntry=journal;
    }
}
